---
- name: Backup folder and send to another server
  hosts: "10.100.10.70"
  gather_facts: false
  connection: local
  tasks:    
    - name: Create a tar.gz backup of the folder
      ansible.builtin.archive:
        path: /var/www/html/upload
        dest: /var/www/html/backup-upload.tar.gz
        format: gz
