---
- name: Backup folder apps
  hosts: all
  gather_facts: false
  connection: local
  tasks:    
    - name: Archive a folder
      shell: "tar -czvf /tmp/my_archive.tar.gz -C / var/www/html/upload"
      args:
        creates: /tmp/my_archive.tar.gz
      become: true


#    - name: Create a tar.gz backup of the folder
#      ansible.builtin.command:
#        cmd: tar -czvf /tmp/backup-upload.tar.gz /var/www/html/upload/
#      delegate_to: localhost

#    - name: Create a tar.gz archive of folder upload in 10.100.10.70.
#      community.general.archive:
#        path: /var/www/html/upload/
#        dest: /tmp/backup-upload.tar.gz
#        format: gz
#        force_archive: true
    - name: get file backup to 10.100.10.70
      fetch:
        src: /tmp/backup-upload.tar.gz
        dest: /var/www/html/backup-upload.tar.gz
        flat: yes
