---
- name: Backup folder and send to another server
  hosts: 10.100.10.70
  gather_facts: false
  connection: local
  tasks:    
    - name: Create a tar.gz backup of the folder
      shell:
        cmd: tar -zcvf /var/www/html/backup-upload.tar.gz /var/www/html/upload
      delegate_to: 10.100.10.70
