---
- name: Checksum file on Source and Destinations
  hosts: all
  gather_facts: false

  tasks:
    - name: Get cksum of my First file on {{ ip_source }}
      delegate_to: "{{ ip_source }}"
      stat:
        path : /tmp/backup-app.tar.gz
      register: myfirstfile

    - name: Current SHA1
      set_fact:
        mf1sha1: "{{ myfirstfile.stat.checksum }}"
      register: chksum_source
    - debug:
        msg: "{{ chksum_source }}"

    - name: Get cksum of my Second File on {{ ip_destination }}
      delegate_to: "{{ ip_destination }}"
      stat:
        path : /var/www/html/file1.txt
      register: mysecondfile

    - name: Current SHA1
      set_fact:
        mf2sha1: "{{ mysecondfile.stat.checksum }}"
      register: chksum_destination
    - debug:
        msg: "{{ chksum_destination }}"

    - name: Compilation Changed
      debug:
        msg: "File Compare"
      failed_when:  mf2sha1 != mf1sha1
