---
- name: Checksum file on Source and Destinations
  hosts: all
  gather_facts: false

  tasks:
    - name: Get checksum of source data from 10.100.10.70
      delegate_to: 10.100.10.7
      stat:
        path : /tmp/backup-app.tar.gz
      register: myfirstfile

    - name: Current SHA1
      set_fact:
        mf1sha1: "{{ myfirstfile.stat.checksum }}"
      register: checksum_firstfile
    - debug:
        msg: "{{ checksum_firstfile }}"

    - name: Get checksum of destination data from 10.100.30.2
      delegate_to: 10.100.30.2
      stat:
        path : /var/www/html/file1.txt
      register: mysecondfile

    - name: Current SHA1
      set_fact:
        mf2sha1: "{{ mysecondfile.stat.checksum }}"
      register: checksum_secondfile
    - debug:
        msg: "{{ checksum_secondfile }}"

    - name: Compilation Changed
      debug:
        msg: "File Compare"
      failed_when:  mf2sha1 != mf1sha1
