---
- name: Checksum file on Source and Destinations
  hosts: all
  gather_facts: false

  tasks:
    - name: Get cksum of my First file on 10.100.10.70
      delegate_to: 10.100.10.70
      stat:
        path : /tmp/backup-app.tar.gz
      register: myfirstfile

    - name: Current SHA1
      set_fact:
        mf1sha1: "{{ myfirstfile.stat.checksum }}"

    - name: Get cksum of my Second File on 10.100.30.2
      delegate_to: 10.100.30.2
      stat:
        path : /var/www/html/backup-app.tar.gz
      register: mysecondfile

    - name: Current SHA1
      set_fact:
        mf2sha1: "{{ mysecondfile.stat.checksum }}"

    - name: Compilation Changed
      debug:
        msg: "File Compare"
      failed_when:  mf2sha1 != mf1sha1
