---
- name: Backup folder apps
  hosts: all
  gather_facts: true
  become: true
  tasks:    
    - name: extract a tar.gz archive of folder upload
      delegate_to: "{{ ip_destination }}"
      unarchive:
        src: /var/www/html/backup-app.tar.gz
        dest: /var/www/html/
        remote_src: yes
    - debug: 
        msg: "extract sukses"

    - name: check file after extract
      delegate_to: "{{ ip_destination }}"
      command: "ls -lh /var/www/html/upload"
      register: output_ls_restoredata
    - debug:
        msg: "{{ output_ls_restoredata }}"
