---
- name: Backup folder apps
  hosts: all
  gather_facts: true
  become: true
  tasks:    
    - name: Create a tar.gz archive of folder upload .
      delegate_to: "{{ ip_destination }}"
      unarchive:
        path: /var/www/html/
        dest: /tmp/backup-app.tar.gz
    - debug: 
        msg: "extract sukses"

    - name: check file after extract
      delegate_to: "{{ ip_destination }}"
      command: "ls -lh /var/www/html/upload"
      register: output_ls_restoredata
    - debug:
        msg: "{{ output_ls_restoredata }}"
