---
- name: move folder apps
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: read file from Server A
      delegate_to: 10.100.10.70
      slurp:
        src: /tmp/backup-upload.tar.gz
      register: file_slurp

    - name: write file to Server B
      delegate_to: 10.100.30.2
      copy:
        content: "{{ file_slurp.content | b64decode }}"
        dest: /var/www/html/{{ file_slurp.source | basename }}"

