---
- name: Backup and Upload to Google Cloud Storage
  hosts: all
  gather_facts: false

  tasks:
    - include_vars:
        file: postgres-account.yaml 

    - name: Dump an existing database to a file from {{ ip_source }}
      delegate_to: "{{ ip_source }}"
      shell:
        cmd: "PGPASSWORD={{ login_password }} pg_dump -U {{ login_user }} -h {{ ip_source_db }} -c uploads > /tmp/backup-db-uploads.tar"
    - debug:
        msg: "Backup Files Database Ready"

    - name: Check file backup database
      delegate_to: "{{ ip_source }}"
      command: "ls -lh /tmp/backup-db-uploads.tar"
      register: output_ls
    - debug:
        msg: "{{ output_ls }}"

    - name: verify google-cloud-storage Python library installed
      pip:
        name: google-cloud-storage
        state: present

    - name: Read file from Server Source
      delegate_to: "{{ ip_source }}"
      slurp:
        src: "/tmp/backup-db-uploads.tar"
      register: file_slurp_db

    - name: write file to temp server
      copy:
        content: "{{ file_slurp_db.content | b64decode }}"
        dest: "/tmp/{{ file_slurp_db.source | basename }}"

    - name: upload backup data from temp server to bucket
      google.cloud.gcp_storage_object:
        action: upload
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: "/tmp/{{ file_slurp_db.source | basename }}"
        dest: "database-backup/{{ file_slurp_db.source | basename }}"
    - debug:
        msg: "Backup database to GCS sukses"
