---
- name: Backup and Upload to Google Cloud Storage
  hosts: all
  gather_facts: false

  tasks:
    - include_vars:
        file: postgres-account.yaml 

    - name: verify google-cloud-storage Python library installed
      pip:
        name: google-cloud-storage
        state: present

    - name: Download database backup from GCS bucket
      google.cloud.gcp_storage_object:
        action: download
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: "database-backup/backup-db-uploads.tar"
        dest: "/tmp/backup-db-uploads.tar"
    - debug:
        msg: "Download database to temp server sukses"

    - name: Check file backup database on temp server
      command: "ls -lh /tmp/backup-db-uploads.tar"
      register: output_ls_temp
    - debug:
        msg: "{{ output_ls_temp }}"

    - name: Read file from Server Source
      slurp:
        src: "/tmp/backup-db-uploads.tar"
      register: file_slurp_db

    - name: write file to temp server
      delegate_to: 10.100.10.70
      copy:
        content: "{{ file_slurp_db.content | b64decode }}"
        dest: "/tmp/{{ file_slurp_db.source | basename }}"

    - name: Check file backup database
      delegate_to: 10.100.10.70
      command: "ls -lh /tmp/{{ file_slurp_db.source | basename }}"
      register: output_ls
    - debug:
        msg: "{{ output_ls }}"

    - name: restore an existing database to a file
      delegate_to: 10.100.10.70
      shell:
        cmd: "PGPASSWORD={{ login_password }} psql -U {{ login_user }} -h 10.100.20.5 -d uploads < /tmp/{{ file_slurp_db.source | basename }}"
    - debug:
        msg: "Restore Files Database Backup Ready"
