---
- name: Download and restore db from Google Cloud Storage
  hosts: all
  gather_facts: false

  tasks:
    - include_vars:
        file: postgres-account.yaml 

#    - name: verify google-cloud-storage Python library installed
#      delegate_to: localhost
#      pip:
#        name: google-cloud-storage
#        state: present

#    - name: "Download backup database from bucket"
#      delegate_to: localhost
#      google.cloud.gcp_storage_object:
#        action: download
#        bucket: backupbjj
#        project: "poc-ansible-bjj"
#        src: database-backup/database.tar
#        dest: "/tmp/database.tar"
#    - debug:
#        msg: "download file backup database to temp sukses"

#    - name: Create a new database if it doesn't exist
#      delegate_to: 10.100.10.70
#      community.postgresql.postgresql_db:
#        login_user: "{{ login_user }}"
#        login_password: "{{ login_password }}"
#        login_host: 10.100.20.5
#        name: uploads
#        state: present

#    - name: Restore Database to a postgres SQL Server
#      delegate_to: 10.100.10.70
#      community.postgresql.postgresql_db:
#        login_host: 10.100.20.5
#        login_user: "{{ login_user }}"
#        login_password: "{{ login_password }}"
#        name: uploads
#        state: restore
#        target: /root/database-backup_database.tar

    - name: verify google-cloud-storage Python library installed
      delegate_to: localhost
      pip:
        name: google-cloud-storage
        state: present

    - name: "download backup data from bucket"
      delegate_to: localhost
      google.cloud.gcp_storage_object:
        action: download
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: database-backup/database.tar
        dest: /tmp/database.tar
    - debug:
        msg: "download to temp sukses"

    - name: read file from temp Source
      delegate_to: localhost
      slurp:
        src: /tmp/database.tar
      register: file_slurp

    - name: write file to Server Target
      delegate_to: 10.100.10.70
      copy:
        content: "{{ file_slurp.content | b64decode }}"
        dest: "/root/{{ file_slurp.source | basename }}"

    - debug:
        msg: "download applications sukses"


    - name: restore from shell psql
      shell:
        cmd: "PGPASSWORD={{ login_password }} pg_restore -U {{ login_user }} -d uploads < /root/{{ file_slurp.source | basename }}"
    - debug:
        msg: "Restore Database Ready"

