---
- name: Remove IAM roles only if roles match for GCP user
  hosts: localhost
  gather_facts: no
  vars:
    project_id: "poc-ansible-bjj"
    user_email: "fathirandy@gmail.com"
    roles:
      - "roles/browser"
      - "roles/editor"
      - "roles/storage.admin"

  tasks:
    - name: Get current IAM policy for the project
      delegate_to: 10.100.10.70
      ansible.builtin.command:
        cmd: >
          gcloud projects get-iam-policy {{ project_id }} --format=json
      register: iam_policy

    - name: Ensure IAM policy is retrieved
      debug:
        msg: "Retrieved IAM policy: {{ iam_policy.stdout }}"

    - name: Remove role only if it matches
      delegate_to: 10.100.10.70
      ansible.builtin.command:
        cmd: >
          gcloud projects remove-iam-policy-binding {{ project_id }}
          --member="user:{{ user_email }}"
          --role="{{ item }}"
      with_items: "{{ roles }}"
      when: >
        (iam_policy.stdout | from_json).bindings | selectattr('role', 'eq', item) |
        map(attribute='members') | flatten() | intersect(["user:{{ user_email }}"]) | length > 0
      register: remove_results

#    - name: Display results of role removal
#      debug:
#        msg: "Role {{ item.item }} removal output: {{ item.stdout }}"
#     with_items: "{{ remove_results.results }}"
