---
- name: download backup files to Google Cloud Storage
  hosts: all
  gather_facts: false

  tasks:
    - name: verify google-cloud-storage Python library installed
      delegate_to: localhost
      pip:
        name: google-cloud-storage
        state: present

    - name: "download backup data from bucket"
      delegate_to: localhost
      google.cloud.gcp_storage_object:
        action: download
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: "databackup.tar.gz"
        dest: "/tmp/databackup.tar.gz"
    - debug:
        msg: "download to temp sukses"

    - name: read file from temp Source
      delegate_to: localhost
      slurp:
        src: /tmp/databackup.tar.gz
      register: file_slurp

    - name: write file to Server Target
      delegate_to: "{{ ip_destination }}"
      copy:
        content: "{{ file_slurp.content | b64decode }}"
        dest: "/var/www/html/{{ file_slurp.source | basename }}"

    - debug:
        msg: "download sukses"

