---
- name: Create instance in GCP
  hosts: localhost
  gather_facts: false
  vars:

  tasks:
    - name: Create a disk
      google.cloud.gcp_compute_disk:
        name: "test-disk"
        size_gb: 50
        source_image: "projects/rhel-cloud/global/images/rhel-8-v20250212"
        zone: "asia-southeast2-a"
        project: "poc-ansible-bjj"
        state: present
      register: disk 

    - name: Create an Instance 
      google.cloud.gcp_compute_instance:
        project: "poc-ansible-bjj"
        state: present
        name: test-ansible
        machine_type: e2-standard-4
        zone: "asia-southeast2-a"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        metadata:
          - key: ssh-keys-mii
            value: user:ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMWWliHh06xJiE3wiLVaRiVSGhudMFjmnB3eNyh0teWuThM4nZrNU2t3VSp7J5wYdSJcmRk5qcAgj1w1SGf3o2k= ecdsa-key-20250306
        network_interfaces:
          - networkIP: "10.100.10.50"
            subnetwork: ansible-bjj
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
                nat_ip: "10.100.10.50"
