---
- name: Create instance in GCP
  hosts: localhost
  connection: local
  gather_facts: false
  vars:

  tasks:
    - name: Create a disk
      google.cloud.gcp_compute_disk:
        name: "test-disk"
        size_gb: 50
        source_image: "projects/rhel-cloud/global/images/rhel-8-v20250212"
        zone: "asia-southeast2-a"
        project: "poc-ansible-bjj"
        state: present
      register: disk 

    - name: Create an Instance 
      google.cloud.gcp_compute_instance:
        project: "poc-ansible-bjj"
        state: present
        name: test-ansible
        machine_type: e2-standard-4
        zone: "asia-southeast2-a"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - networkIP: "10.100.10.50"
            subnetwork:
              selfLink: "projects/poc-ansible-bjj/regions/asia-southeast2/subnetworks/ansible-bjj"
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
                nat_ip:
                  address: "10.100.10.50"
