---
- name: Create static ip
  hosts: localhost
  gather_facts: false
  vars:
    subnet: projects/poc-ansible-bjj/regions/asia-southeast2/subnetworks/bjj
    network: poc-ansible-bjj
  tasks:
    - name: create a static ip address
      google.cloud.gcp_compute_address:
        name: mystaticip
        region: asia-southeast2
        project: poc-ansible-bjj
        state: present
        address_type: INTERNAL
        address: "10.100.10.50"
        auth_kind: serviceaccount
        service_account_file: "/root/git/bjj/gcp/poc-ansible-bjj-d2fbdf60ef03.json"
        network:
          selfLink: projects/poc-ansible-bjj/global/networks/poc-ansible-bjj
        subnetwork:
          selfLink: "projects/poc-ansible-bjj/regions/asia-southeast2/subnetworks/ansible-bjj"
      register: address

    - name: Print Reserved IP Address
      debug:
        var: address
