---
- name: Create static ip
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create a static ip address
      google.cloud.gcp_compute_address:
        name: "{{ name_compute_engine }}"
        region: asia-southeast2
        project: poc-ansible-bjj
        state: present
        address_type: "{{ address_type }}"
        address: "{{ ipaddress }}"
#        network:
#          selfLink: "projects/poc-ansible-bjj/global/networks/poc-ansible-bjj"
        subnetwork:
          selfLink: "projects/poc-ansible-bjj/regions/asia-southeast2/subnetworks/{{ subnetwork }}"  #define subnetwork
      register: address_static

    - name: Print Reserved IP Address
      debug:
        var: address_static
