---
- name: Create static ip
  hosts: localhost
  gather_facts: false
  vars:
    subnetwork_self_link: "subnetworks/bjj"


  tasks:
    - name: create a static ip address
      google.cloud.gcp_compute_address:
        name: mystaticip
        region: asia-southeast2
        project: poc-ansible-bjj
        state: present
        address_type: INTERNAL
        address: "10.100.50.50"
        network: poc-ansible-bjj
        subnetwork: "{{ subnetwork_self_link }}"
      register: address

    - name: Print Reserved IP Address
      debug:
        var: address
