---
- name: Create static ip
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create a static ip address
      google.cloud.gcp_compute_address:
        name: "{{ name-ip-address }}"        #define name
        region: asia-southeast2
        project: poc-ansible-bjj
        state: present
        address_type: "{{ address-type }}"     #define INTERNAL or EXTERNAL
        address: "{{ ip-address }]"            #fill ip address sample 10.100.10.50
#        network:
#          selfLink: "projects/poc-ansible-bjj/global/networks/poc-ansible-bjj"
        prefix_length: "{{ ip-address-range }}"      #prefix sesuai zone
        subnetwork:
          selfLink: "projects/poc-ansible-bjj/regions/asia-southeast2/subnetworks/{{ subnetwork }}"  #define subnetwork
      register: address

    - name: Print Reserved IP Address
      debug:
        var: address
