---
- name: Create instance in GCP
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Update A record IP address
      google.cloud.gcp_dns_resource_record_set:
        project: "poc-ansible-bjj"
        managed_zone:
          name: miilabcoid
          dnsName: miilab.co.id
        name: demo.miilab.co.id.
        type: A
        ttl: 300
        target:
          - 10.100.30.2
        state: present
#        overwrite: true
