---
- name: Upload backup files to Google Cloud Storage
  hosts: localhost
#  connection: local
  gather_facts: false

  tasks:
    - name: verify python3-pip installed
      delegate_to: 10.100.10.70
      dnf:
        name:
          - python3-dnf
          - python3-pip
        state: present
#    - name: wait for VM to be ready
#      wait_for: timeout=30
#      delegate_to: localhost

    - name: verify google-cloud-storage Python library installed
      delegate_to: 10.100.10.70
      pip:
        name: google-cloud-storage
        state: present

    - name: read file from Server Source
      delegate_to: "10.100.10.70"
      slurp:
        src: /tmp/backup-upload.tar.gz
      register: file_slurp

    - name: write file to Server B
#      delegate_to: "{{ ipdestination }}"
      copy:
        content: "{{ file_slurp.content | b64decode }}"
        dest: "/tmp/{{ file_slurp.source | basename }}"

    - name: "Update backup data to bucket"
      google.cloud.gcp_storage_object:
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: "/tmp/{{ file_slurp.source | basename }}"
        dest: "~/databackup.tar.gz"
    - debug:
        msg: "backup sukses"

