---
- name: Upload backup files to Google Cloud Storage
  hosts: localhost
  gather_facts: false

  tasks:
    - name: verify google-cloud-storage Python library installed
      pip:
        name: google-cloud-storage
        state: present

    - name: read file from Server Source
      delegate_to: "ip_source"
      slurp:
        src: /tmp/databackup.tar.gz
      register: file_slurp

    - name: write file to Server B
      copy:
        content: "{{ file_slurp.content | b64decode }}"
        dest: "/tmp/{{ file_slurp.source | basename }}"

    - name: upload backup data to bucket
      google.cloud.gcp_storage_object:
        action: upload
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: "/tmp/{{ file_slurp.source | basename }}"
        dest: "databackup.tar.gz"
    - debug:
        msg: "backup sukses"

