---
- name: Upload backup files to Google Cloud Storage
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: verify google cloud storage python
      delegate_to: 10.100.10.70
      pip:
        name: google-cloud-storage
        state: present
    - name: "Update backup data to bucket {{ nama_bucket }}"
      delegate_to: 10.100.10.70
      google.cloud.gcp_storage_object:
        bucket: backupbjj
        project: "poc-ansible-bjj"
        src: /tmp/databackup.tar.gz
        dest: "~/databackup.tar.gz"
    - debug:
        msg: "backup sukses"

