---
- name: Upload backup files to Google Cloud Storage
  hosts: localhost
#  connection: local
  gather_facts: false

  tasks:
    - name: verify python3-pip installed
      delegate_to: 10.100.10.70
      dnf:
        name:
          - python3-dnf
          - python3-pip
        state: present
#    - name: wait for VM to be ready
#      wait_for: timeout=30
#      delegate_to: localhost

    - name: verify google-cloud-storage Python library installed
      delegate_to: 10.100.10.70
      pip:
        name: google-cloud-storage
        state: present
#    - name: "Update backup data to bucket {{ nama_bucket }}"
#      delegate_to: 10.100.10.70
#      google.cloud.gcp_storage_object:
#        bucket: backupbjj
#        project: "poc-ansible-bjj"
#        src: /tmp/databackup.tar.gz
#        dest: "~/databackup.tar.gz"
#    - debug:
#        msg: "backup sukses"

